apiVersion: v1
kind: Service
metadata:
  name: {{ include "pactbroker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pactbroker.name" . }}
    helm.sh/chart: {{ include "pactbroker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.serviceLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end}}
  {{- with .Values.service.annotations }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pactbroker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
